Implement oauth2
testmycode/tmc-core pull request #117
Opened 2016-12-07 09:36 UTC by Rochet2

Implements oauth2 authentication using password flow by default. (there can be other ways of authentication than with username and password)
This can co-exist with the basic auth.

- Adds a new library for oauth
- Implements needed classes for the oauth authentication (made it use classes in case other flows are used in future)
- Adds oauth to the core code - token fetch can error and this forces moving of some parts of code to inside of callable's call function.
- Wraps existing tasks with tryCallCallable, which will try execute the task when requested and if the request fails, it fetches a new token and tries again.

The TmcSettings must define if they use oauth, the oauth token url, oauth application id and secret.
Also the password flow requires the username and password to be defined.

@testmycode/api-team

2016-12-07 22:56 UTC, nygrenh requested changes

2016-12-07 22:56 UTC, nygrenh commented on src/main/java/fi/helsinki/cs/tmc/core/communication/TmcServerCommunicationTaskFactory.java
> +    public static Oauth oauth = new Oauth(new PasswordFlow());
- final
- why static?

2016-12-07 22:56 UTC, nygrenh commented on src/main/java/fi/helsinki/cs/tmc/core/communication/TmcServerCommunicationTaskFactory.java
> +                    oauth.refreshToken();
Maybe log this?

2016-12-07 22:56 UTC, nygrenh commented on src/main/java/fi/helsinki/cs/tmc/core/communication/TmcServerCommunicationTaskFactory.java
> +    private <T> Callable<T> tryCallCallable(final Callable<T> callable) {
Maybe give this method a name that makes it clear that the intention of this method is to call a callable with an oauth token.

2016-12-07 22:56 UTC, nygrenh commented on src/main/java/fi/helsinki/cs/tmc/core/communication/oauth2/Oauth.java
> +    public String getToken() throws Exception {
Is it possible to throw a more specific exception?

2016-12-07 22:56 UTC, nygrenh commented on src/main/java/fi/helsinki/cs/tmc/core/communication/oauth2/Oauth.java
> +    public String refreshToken() throws Exception {
Is it possible to throw a more specific exception?

2016-12-07 22:56 UTC, nygrenh commented on src/main/java/fi/helsinki/cs/tmc/core/communication/oauth2/OauthFlow.java
> +    public String getToken() throws Exception;
Is it possible to throw a more specific exception?

2016-12-07 22:56 UTC, nygrenh commented on src/main/java/fi/helsinki/cs/tmc/core/communication/oauth2/PasswordFlow.java
> +        TmcSettings settings = TmcSettingsHolder.get();
A field in the class?

2016-12-07 22:56 UTC, nygrenh commented on src/main/java/fi/helsinki/cs/tmc/core/communication/oauth2/PasswordFlow.java
> +        String token = client.accessToken(request, OAuthJSONAccessTokenResponse.class)
Logging

2016-12-08 07:51 UTC, Rochet2 commented on src/main/java/fi/helsinki/cs/tmc/core/communication/TmcServerCommunicationTaskFactory.java
> +    public static Oauth oauth = new Oauth(new PasswordFlow());
It is static because it remembers the token.
On each call to an endpoint a new TmcServerCommunicationTaskFactory is created so the variable must be static to persist.

Either there is a static/global variable somewhere or the auth is passed around everywhere.

2016-12-08 07:54 UTC, Rochet2 commented on src/main/java/fi/helsinki/cs/tmc/core/communication/oauth2/Oauth.java
> +    public String getToken() throws Exception {
Yes and no. There is no more specific exception that all the exceptions would inherit.
But we could maybe list all the exceptions thrown to be more specific about what all could be thrown. The same list would be needed to be added to some other parts in the code as well though.

2016-12-08 07:56 UTC, Rochet2 commented on src/main/java/fi/helsinki/cs/tmc/core/communication/oauth2/PasswordFlow.java
> +        TmcSettings settings = TmcSettingsHolder.get();
The reason I did not use a field here was that oauth is static in TmcServerCommunicationTaskFactory and settings may not be available when the variable is initialized.
One possibility could be to get rid of the staticness in some way or to cache the settings which feels relatively pointless.

2016-12-08 08:02 UTC, Rochet2 commented on src/main/java/fi/helsinki/cs/tmc/core/communication/TmcServerCommunicationTaskFactory.java
> +                    oauth.refreshToken();
Can you be more specific about what you mean with logging?
Do you mean using this? https://github.com/testmycode/tmc-core/blob/c54d76b6f0430404b1d2e564f3754a24fc3746a6/src/main/java/fi/helsinki/cs/tmc/spyware/EventStore.java#L26 or what with should it be logged?

2016-12-08 08:02 UTC, Rochet2 commented on src/main/java/fi/helsinki/cs/tmc/core/communication/oauth2/PasswordFlow.java
> +        String token = client.accessToken(request, OAuthJSONAccessTokenResponse.class)
Can you be more specific about why and what should be logged?
I can only assume token needs to be outputted for some debugging purposes.
Also an earlier comment was asking how to log.

2016-12-08 08:08 UTC, nygrenh commented on src/main/java/fi/helsinki/cs/tmc/core/communication/TmcServerCommunicationTaskFactory.java
> +                    oauth.refreshToken();
Like that but something like "the oauth token is not valid, refreshing" (or whatever that branch implies, I cannot remember)

2016-12-08 08:10 UTC, nygrenh commented on src/main/java/fi/helsinki/cs/tmc/core/communication/oauth2/PasswordFlow.java
> +        String token = client.accessToken(request, OAuthJSONAccessTokenResponse.class)
Logging that you're fetching a new token

2016-12-08 08:13 UTC, nygrenh commented on src/main/java/fi/helsinki/cs/tmc/core/communication/oauth2/Oauth.java
> +    public String getToken() throws Exception {
How long would the list be?

2016-12-08 09:48 UTC, Rochet2 commented on src/main/java/fi/helsinki/cs/tmc/core/communication/oauth2/Oauth.java
> +    public String getToken() throws Exception {
It seems that probably `throws OAuthSystemException, OAuthProblemException, OAuthRuntimeException` is the longest list needed atm.

2016-12-08 11:13 UTC, jamo commented on src/main/java/fi/helsinki/cs/tmc/core/communication/TmcServerCommunicationTaskFactory.java
> +                    oauth.refreshToken();
Do we really want to refresh token for all possible exceptions thrown?

2016-12-08 11:51 UTC, Rochet2 commented on src/main/java/fi/helsinki/cs/tmc/core/communication/TmcServerCommunicationTaskFactory.java
> +                    oauth.refreshToken();
At minimum we need to refresh it on `FailedHttpResponseException` when status code is 403 or 401.
But I am unsure what all others we would need to prepare for. There could be more status codes or exceptions. The ones mentioned are caused by authorize! and normal no access (forbidden) which I feel could be enough. Cant think of additional cases where token needs refreshing as those are the ones that get triggered when trying to access stuff as a guest or wrong user with no access.

2016-12-08 11:55 UTC, Rochet2 commented
unresolved comments:
https://github.com/testmycode/tmc-core/pull/117#discussion_r91403473 (static auth variable)
https://github.com/testmycode/tmc-core/pull/117#discussion_r91493412 (refreshing token in which exceptions / situations)
https://github.com/testmycode/tmc-core/pull/117#discussion_r91405953 (how to get settings in flow)

2016-12-08 13:56 UTC, nygrenh commented on src/main/java/fi/helsinki/cs/tmc/core/communication/oauth2/PasswordFlow.java
> +        TmcSettings settings = TmcSettingsHolder.get();
If that's the case, maybe we should replace the static oauth with the `getInstance` pattern

2016-12-08 14:04 UTC, nygrenh commented on src/main/java/fi/helsinki/cs/tmc/core/communication/oauth2/PasswordFlow.java
> +        LOG.log(Level.INFO, "Fetching new token from server");
Can you mention that it is fetching the *oauth* token

2016-12-08 14:07 UTC, nygrenh commented on src/main/java/fi/helsinki/cs/tmc/core/communication/oauth2/Oauth.java
> +    public String getToken() throws Exception {
Then we should just throw all of them since we may want to handle these cases in different ways.

2016-12-14 12:21 UTC, nygrenh approved these changes

2016-12-14 12:22 UTC, merged