Download adaptive exercises.
testmycode/tmc-core pull request #119
Opened 2017-05-22 08:23 UTC by Mavai

2017-05-22 12:04 UTC, Redande commented
Got the following checkstyle errors from running `mvn checkstyle:check`:

```
[ERROR] src/main/java/fi/helsinki/cs/tmc/spyware/EventSendBuffer.java:[28] (whitespace) EmptyLineSeparator: 'import' should be separated from previous statement.
[ERROR] src/main/java/fi/helsinki/cs/tmc/spyware/EventSendBuffer.java:[28] (imports) CustomImportOrder: Import statement for 'com.google.common.base.Preconditions.checkArgument' is in the wrong order. Should be in the 'STATIC' group, expecting not assigned imports on this line.
[ERROR] src/main/java/fi/helsinki/cs/tmc/core/TmcCore.java:[7] (imports) CustomImportOrder: Wrong lexicographical order for 'fi.helsinki.cs.tmc.core.commands.DownloadAdaptiveExercise' import. Should be before 'fi.helsinki.cs.tmc.core.commands.DownloadOrUpdateExercises'.
[ERROR] src/main/java/fi/helsinki/cs/tmc/core/TmcCore.java:[42] (imports) CustomImportOrder: Import statement for 'fi.helsinki.cs.tmc.core.commands.Command' is in the wrong order. Should be in the 'SPECIAL_IMPORTS' group, expecting group 'STANDARD_JAVA_PACKAGE' on this line.
[ERROR] src/main/java/fi/helsinki/cs/tmc/core/communication/TmcServerCommunicationTaskFactory.java:[3] (imports) AvoidStarImport: Using the '.*' form of import should be avoided - fi.helsinki.cs.tmc.core.commands.*.
[ERROR] src/main/java/fi/helsinki/cs/tmc/core/communication/TmcServerCommunicationTaskFactory.java:[161,64] (whitespace) SeparatorWrap: '.' should be on a new line.
[ERROR] src/main/java/fi/helsinki/cs/tmc/core/communication/TmcServerCommunicationTaskFactory.java:[165,17] (blocks) RightCurly: '}' at column 17 should be on the same line as the next part of a multi-block statement.
[ERROR] src/test/java/fi/helsinki/cs/tmc/core/spyware/EventSendBufferTest.java:[46] (whitespace) EmptyLineSeparator: 'import' should be separated from previous statement.
[ERROR] src/test/java/fi/helsinki/cs/tmc/core/spyware/EventSendBufferTest.java:[46] (imports) CustomImportOrder: Import statement for 'org.junit.Assert.assertArrayEquals' is in the wrong order. Should be in the 'STATIC' group, expecting not assigned imports on this line.
[ERROR] src/test/java/fi/helsinki/cs/tmc/core/spyware/EventSendBufferTest.java:[47] (imports) CustomImportOrder: Import statement for 'org.junit.Assert.assertEquals' is in the wrong order. Should be in the 'STATIC' group, expecting not assigned imports on this line.
[ERROR] src/test/java/fi/helsinki/cs/tmc/core/spyware/EventSendBufferTest.java:[48] (imports) CustomImportOrder: Import statement for 'org.junit.Assert.assertTrue' is in the wrong order. Should be in the 'STATIC' group, expecting not assigned imports on this line.
[ERROR] src/test/java/fi/helsinki/cs/tmc/core/spyware/EventSendBufferTest.java:[49] (imports) CustomImportOrder: Import statement for 'org.junit.Assert.fail' is in the wrong order. Should be in the 'STATIC' group, expecting not assigned imports on this line.
[ERROR] src/test/java/fi/helsinki/cs/tmc/core/spyware/EventSendBufferTest.java:[50] (imports) CustomImportOrder: Import statement for 'org.mockito.Matchers.any' is in the wrong order. Should be in the 'STATIC' group, expecting not assigned imports on this line.
[ERROR] src/test/java/fi/helsinki/cs/tmc/core/spyware/EventSendBufferTest.java:[51] (imports) CustomImportOrder: Import statement for 'org.mockito.Mockito.verify' is in the wrong order. Should be in the 'STATIC' group, expecting not assigned imports on this line.
[ERROR] src/test/java/fi/helsinki/cs/tmc/core/commands/GetUpdatableExercisesTest.java:[35] (whitespace) EmptyLineSeparator: 'import' should be separated from previous statement.
[ERROR] src/test/java/fi/helsinki/cs/tmc/core/commands/GetUpdatableExercisesTest.java:[35] (imports) CustomImportOrder: Import statement for 'com.google.common.truth.Truth.assertThat' is in the wrong order. Should be in the 'STATIC' group, expecting not assigned imports on this line.
[ERROR] src/test/java/fi/helsinki/cs/tmc/core/commands/GetUpdatableExercisesTest.java:[36] (imports) CustomImportOrder: Import statement for 'org.junit.Assert.assertEquals' is in the wrong order. Should be in the 'STATIC' group, expecting not assigned imports on this line.
[ERROR] src/test/java/fi/helsinki/cs/tmc/core/commands/GetUpdatableExercisesTest.java:[37] (imports) CustomImportOrder: Import statement for 'org.junit.Assert.assertNotEquals' is in the wrong order. Should be in the 'STATIC' group, expecting not assigned imports on this line.
[ERROR] src/test/java/fi/helsinki/cs/tmc/core/commands/GetUpdatableExercisesTest.java:[38] (imports) CustomImportOrder: Import statement for 'org.mockito.Matchers.any' is in the wrong order. Should be in the 'STATIC' group, expecting not assigned imports on this line.
[ERROR] src/test/java/fi/helsinki/cs/tmc/core/commands/AuthenticateUserTest.java:[32] (whitespace) EmptyLineSeparator: 'import' should be separated from previous statement.
[ERROR] src/test/java/fi/helsinki/cs/tmc/core/commands/AuthenticateUserTest.java:[32] (imports) CustomImportOrder: Import statement for 'org.junit.Assert.assertEquals' is in the wrong order. Should be in the 'STATIC' group, expecting not assigned imports on this line.
[ERROR] src/test/java/fi/helsinki/cs/tmc/core/commands/AuthenticateUserTest.java:[33] (imports) CustomImportOrder: Import statement for 'org.junit.Assert.assertTrue' is in the wrong order. Should be in the 'STATIC' group, expecting not assigned imports on this line.
[ERROR] src/test/java/fi/helsinki/cs/tmc/core/commands/AuthenticateUserTest.java:[34] (imports) CustomImportOrder: Import statement for 'org.mockito.Mockito.verify' is in the wrong order. Should be in the 'STATIC' group, expecting not assigned imports on this line.
[ERROR] src/test/java/fi/helsinki/cs/tmc/core/commands/PasteWithCommentTest.java:[36] (whitespace) EmptyLineSeparator: 'import' should be separated from previous statement.
[ERROR] src/test/java/fi/helsinki/cs/tmc/core/commands/PasteWithCommentTest.java:[36] (imports) CustomImportOrder: Import statement for 'org.junit.Assert.assertEquals' is in the wrong order. Should be in the 'STATIC' group, expecting not assigned imports on this line.
[ERROR] src/test/java/fi/helsinki/cs/tmc/core/commands/PasteWithCommentTest.java:[37] (imports) CustomImportOrder: Import statement for 'org.mockito.Matchers.any' is in the wrong order. Should be in the 'STATIC' group, expecting not assigned imports on this line.
[ERROR] src/test/java/fi/helsinki/cs/tmc/core/commands/GetCourseDetailsTest.java:[22] (whitespace) EmptyLineSeparator: 'import' should be separated from previous statement.
[ERROR] src/test/java/fi/helsinki/cs/tmc/core/commands/GetCourseDetailsTest.java:[22] (imports) CustomImportOrder: Import statement for 'com.google.common.truth.Truth.assertThat' is in the wrong order. Should be in the 'STATIC' group, expecting not assigned imports on this line.
[ERROR] src/test/java/fi/helsinki/cs/tmc/core/commands/DownloadOrUpdateExercisesTest.java:[41] (whitespace) EmptyLineSeparator: 'import' should be separated from previous statement.
[ERROR] src/test/java/fi/helsinki/cs/tmc/core/commands/DownloadOrUpdateExercisesTest.java:[41] (imports) CustomImportOrder: Import statement for 'com.google.common.truth.Truth.assertThat' is in the wrong order. Should be in the 'STATIC' group, expecting not assigned imports on this line.
[ERROR] src/test/java/fi/helsinki/cs/tmc/core/commands/DownloadOrUpdateExercisesTest.java:[42] (imports) CustomImportOrder: Import statement for 'org.junit.Assert.assertFalse' is in the wrong order. Should be in the 'STATIC' group, expecting not assigned imports on this line.
[ERROR] src/test/java/fi/helsinki/cs/tmc/core/commands/DownloadOrUpdateExercisesTest.java:[43] (imports) CustomImportOrder: Import statement for 'org.junit.Assert.assertTrue' is in the wrong order. Should be in the 'STATIC' group, expecting not assigned imports on this line.
[ERROR] src/test/java/fi/helsinki/cs/tmc/core/commands/DownloadOrUpdateExercisesTest.java:[44] (imports) CustomImportOrder: Import sta [...]

2017-05-22 12:24 UTC, nygrenh requested changes
There were some issues that need to be resolved.

2017-05-22 12:24 UTC, nygrenh commented on src/main/java/fi/helsinki/cs/tmc/core/commands/DownloadAdaptiveExercise.java
> + * Author: Ohtu Summer devs 2017
We don't use this kind of banners.

2017-05-22 12:24 UTC, nygrenh commented on src/main/java/fi/helsinki/cs/tmc/core/commands/DownloadAdaptiveExercise.java
> +    private static final Logger logger = LoggerFactory.getLogger(SendFeedback.class);
This logger uses the wrong class. It should be `DownloadAdaptiveExercise.class`

2017-05-22 12:24 UTC, nygrenh commented on src/main/java/fi/helsinki/cs/tmc/core/commands/DownloadAdaptiveExercise.java
> +        //informObserver("MOI");
Redundant comment

2017-05-22 12:24 UTC, nygrenh commented on src/main/java/fi/helsinki/cs/tmc/core/commands/DownloadAdaptiveExercise.java
> +        //Tallennuspolku riippuu edellämainituista nimistä, polku: maindirectory/courseName/exerciseName
Weird language

2017-05-22 12:24 UTC, nygrenh commented on src/main/java/fi/helsinki/cs/tmc/core/commands/DownloadAdaptiveExercise.java
> +        //checkInterrupt();
Dead code?

2017-05-22 12:24 UTC, nygrenh commented on src/main/java/fi/helsinki/cs/tmc/core/commands/DownloadAdaptiveExercise.java
> +        System.out.println(zipb.length);
Unnecessary printing.

2017-05-22 12:24 UTC, nygrenh commented on src/main/java/fi/helsinki/cs/tmc/core/communication/TmcServerCommunicationTaskFactory.java
> +import fi.helsinki.cs.tmc.core.commands.*;
No wildcard imports.

2017-05-22 12:24 UTC, nygrenh commented on src/main/java/fi/helsinki/cs/tmc/core/commands/DownloadAdaptiveExercise.java
> +        Progress progress = new Progress(3);
Why 3?

2017-05-22 12:24 UTC, nygrenh commented on src/main/java/fi/helsinki/cs/tmc/core/communication/TmcServerCommunicationTaskFactory.java
> +
Why are you adding this whitespace?

2017-05-22 12:24 UTC, nygrenh commented on src/main/java/fi/helsinki/cs/tmc/core/communication/TmcServerCommunicationTaskFactory.java
> +                    //Testit menee lävitse generaattorilla luodulla json tiedostolla.
Weird language

2017-05-22 12:24 UTC, nygrenh commented on src/main/java/fi/helsinki/cs/tmc/core/communication/TmcServerCommunicationTaskFactory.java
> +                    return null;
Maybe log the exception?

2017-05-22 12:24 UTC, nygrenh commented on src/main/java/fi/helsinki/cs/tmc/core/communication/TmcServerCommunicationTaskFactory.java
> +                                        getForText(URI.create("http://ohtu-skillifier.herokuapp.com/next.json"));
The url should be a constant at the top of the class.

2017-05-22 12:24 UTC, nygrenh commented on src/main/java/fi/helsinki/cs/tmc/core/communication/TmcServerCommunicationTaskFactory.java
> +
Unnecessary addition

2017-05-22 12:24 UTC, nygrenh commented on src/main/java/fi/helsinki/cs/tmc/core/communication/http/HttpRequestExecutor.java
> +    public HttpUriRequest request;
Why did you change this?

2017-05-22 12:24 UTC, nygrenh commented on src/main/java/fi/helsinki/cs/tmc/core/communication/serialization/AdaptiveExerciseParser.java
> + * Author: Ohtu project summer devs 2017
No unnecessary banners

2017-05-22 12:24 UTC, nygrenh commented on src/main/java/fi/helsinki/cs/tmc/core/communication/serialization/AdaptiveExerciseParser.java
> +public class AdaptiveExerciseParser {
This should be a GSON model class.

2017-05-22 12:24 UTC, nygrenh commented on src/main/java/fi/helsinki/cs/tmc/spyware/EventSendBuffer.java
> +import static com.google.common.base.Preconditions.checkArgument;
Why did you add this?

2017-05-22 12:24 UTC, nygrenh commented on src/test/java/fi/helsinki/cs/tmc/core/commands/AuthenticateUserTest.java
> +import static org.junit.Assert.assertTrue;
Why did you add these?

2017-05-22 12:24 UTC, nygrenh commented on src/test/java/fi/helsinki/cs/tmc/core/commands/DownloadAdaptiveExerciseTest.java
> + * To change this template file, choose Tools | Templates
Unnecessary comment.

2017-05-22 12:24 UTC, nygrenh commented on src/test/java/fi/helsinki/cs/tmc/core/commands/DownloadAdaptiveExerciseTest.java
> + * @author fogh.
Unnecessary comment

2017-05-22 12:24 UTC, nygrenh commented on src/test/java/fi/helsinki/cs/tmc/core/commands/DownloadOrUpdateExercisesTest.java
> +import static org.junit.Assert.assertTrue;
Why did you add these?

2017-05-22 12:24 UTC, nygrenh commented on src/test/java/fi/helsinki/cs/tmc/core/commands/GetCourseDetailsTest.java
> +import static com.google.common.truth.Truth.assertThat;
Why did you add this?

2017-05-22 12:24 UTC, nygrenh commented on src/test/java/fi/helsinki/cs/tmc/core/commands/GetOrganizationsTest.java
> +import static org.mockito.Mockito.verify;
Why did you add this?

2017-05-22 12:24 UTC, nygrenh commented on src/test/java/fi/helsinki/cs/tmc/core/commands/GetUpdatableExercisesTest.java
> +import static org.junit.Assert.assertNotEquals;
Why did you add these?

2017-05-22 12:24 UTC, nygrenh commented on src/test/java/fi/helsinki/cs/tmc/core/commands/ListCoursesTest.java
> +import static com.google.common.truth.Truth.assertThat;
Why did you add this?

2017-05-22 12:24 UTC, nygrenh commented on src/test/java/fi/helsinki/cs/tmc/core/commands/PasteWithCommentTest.java
> +import static org.junit.Assert.assertEquals;
Why did you add these?

2017-05-22 12:24 UTC, nygrenh commented on src/test/java/fi/helsinki/cs/tmc/core/commands/SendFeedbackTest.java
> +import static org.junit.Assert.assertTrue;
Why did you add these?

2017-05-22 12:24 UTC, nygrenh commented on src/test/java/fi/helsinki/cs/tmc/core/commands/SubmitTest.java
> +import static org.mockito.Matchers.any;
I think you know what I mean

2017-05-22 12:24 UTC, nygrenh commented on src/test/java/fi/helsinki/cs/tmc/core/communication/http/serialization/AdaptiveExerciseParserTest.java
> + * Author: Ohtu project summer devs 2017
Unnecessary comment.

2017-05-22 12:24 UTC, nygrenh commented on src/test/java/fi/helsinki/cs/tmc/core/communication/http/serialization/AdaptiveExerciseParserTest.java
> +        assertEquals(exercise.getDownloadUrl().toString(), "http://localhost:3200additionToString");
Dont assert with locahost

2017-05-22 12:24 UTC, nygrenh commented on src/test/java/fi/helsinki/cs/tmc/core/communication/http/serialization/AdaptiveExerciseParserTest.java
> +    public void exerciseHasZipUrl() {
Missing test annotation so this is not getting run

2017-05-22 12:24 UTC, nygrenh commented on src/test/java/fi/helsinki/cs/tmc/core/spyware/EventSendBufferTest.java
> +import static org.junit.Assert.fail;
Unnecessary imports.

2017-05-22 12:25 UTC, ljleppan commented on src/main/java/fi/helsinki/cs/tmc/core/TmcCore.java
> +import fi.helsinki.cs.tmc.core.commands.Command;
Organize imports

2017-05-22 12:29 UTC, ljleppan commented on src/main/java/fi/helsinki/cs/tmc/core/communication/serialization/AdaptiveExerciseParser.java
> +                // localhost, where is Skillifier hosted?
Unnecessary comment + seems to be out of sync with code?

2017-05-22 12:33 UTC, ljleppan commented on src/test/java/fi/helsinki/cs/tmc/core/commands/GetUpdatableExercisesTest.java
> +import static org.mockito.Matchers.any;
Organize imports (chech other places as well)

2017-05-22 12:38 UTC, ljleppan commented
Consider squashing the commits (or equiv.), messages like "pls work" are fine in temporary branches but I'd rather avoid them in the master branch.

2017-05-23 07:02 UTC, Mavai commented on src/main/java/fi/helsinki/cs/tmc/core/commands/DownloadAdaptiveExercise.java
> + * Author: Ohtu Summer devs 2017
Fixed.

2017-05-23 07:02 UTC, Mavai commented on src/main/java/fi/helsinki/cs/tmc/core/commands/DownloadAdaptiveExercise.java
> +    private static final Logger logger = LoggerFactory.getLogger(SendFeedback.class);
Fixed.

2017-05-23 07:03 UTC, Mavai commented on src/main/java/fi/helsinki/cs/tmc/core/commands/DownloadAdaptiveExercise.java
> +        //informObserver("MOI");
Fixed.

2017-05-23 07:03 UTC, Mavai commented on src/main/java/fi/helsinki/cs/tmc/core/commands/DownloadAdaptiveExercise.java
> +        System.out.println(zipb.length);
Fixed.

2017-05-23 07:04 UTC, Mavai commented on src/main/java/fi/helsinki/cs/tmc/core/communication/TmcServerCommunicationTaskFactory.java
> +import fi.helsinki.cs.tmc.core.commands.*;
Fixed.

2017-05-23 07:06 UTC, Mavai commented on src/main/java/fi/helsinki/cs/tmc/core/commands/DownloadAdaptiveExercise.java
> +        //Tallennuspolku riippuu edellämainituista nimistä, polku: maindirectory/courseName/exerciseName
Fixed.

2017-05-23 07:07 UTC, Mavai commented on src/main/java/fi/helsinki/cs/tmc/core/communication/TmcServerCommunicationTaskFactory.java
> +                    //Testit menee lävitse generaattorilla luodulla json tiedostolla.
Fixed.

2017-05-23 07:14 UTC, Mavai commented on src/main/java/fi/helsinki/cs/tmc/core/communication/TmcServerCommunicationTaskFactory.java
> +                                        getForText(URI.create("http://ohtu-skillifier.herokuapp.com/next.json"));
Fixed.

2017-05-23 07:28 UTC, Mavai commented on src/main/java/fi/helsinki/cs/tmc/core/communication/TmcServerCommunicationTaskFactory.java
> +                    return null;
Fixed.

2017-05-26 13:12 UTC, ljleppan requested changes
A few more notes. Also, where is test.zip used?

2017-05-26 13:12 UTC, ljleppan commented on src/main/java/fi/helsinki/cs/tmc/core/commands/DownloadAdaptiveExercise.java
> +        exercise.setCourseName("None");
What is the purpose of these two lines? 

They read to me like temporary values for development environment testing. 
I assume that the API you are interacting with is supposed to also tell you these values. If so, set them preferably in `AdaptiveExerciseParser`. If not, consider making that change.

2017-05-26 13:12 UTC, ljleppan commented on src/main/java/fi/helsinki/cs/tmc/core/commands/DownloadAdaptiveExercise.java
> +        //checkInterrupt();
Dead code,  but checking for interruptions might be a good idea.

2017-05-26 13:12 UTC, ljleppan commented on src/main/java/fi/helsinki/cs/tmc/core/communication/TmcServerCommunicationTaskFactory.java
> +        // "/core/org/" => "/core/org"
This comment doesn't really make sense outside of this diff.

2017-05-26 13:12 UTC, ljleppan commented on src/main/java/fi/helsinki/cs/tmc/core/communication/TmcServerCommunicationTaskFactory.java
> +                    LOG.log(Level.WARNING, "Downloading and parsing adaptive exercise URL failed.");
Also log the actual exception

2017-05-26 13:12 UTC, ljleppan commented on src/main/java/fi/helsinki/cs/tmc/core/exceptions/ExtractingExerciseFailedException.java
> +    // extract exercise when name is unknown,
I don't understand this comment. Remove or make clearer.

2017-05-26 13:12 UTC, ljleppan commented on src/test/java/fi/helsinki/cs/tmc/core/commands/DownloadAdaptiveExerciseTest.java
> +        Path testPath = Paths.get(System.getProperty("user.dir"));
Don't add stuff to my home directory and **especially** do not delete stuff from there (Line 142).

Use [`java.nio.file.Files#createTempDirectory`](http://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#createTempDirectory-java.lang.String-java.nio.file.attribute.FileAttribute...-) instead, specifically the version that uses the system's default temporary directory.

2017-05-30 11:11 UTC, closed without merging