Added theme model to core
testmycode/tmc-core pull request #122
Opened 2017-06-07 11:11 UTC by Forbaya

This is the result of our sprint 2.

2017-06-07 11:53 UTC, ljleppan requested changes

2017-06-07 11:53 UTC, ljleppan commented on src/main/java/fi/helsinki/cs/tmc/core/commands/SubmitAdaptiveExerciseToSkillifier.java
> +                //"/exercises/" + exercise.getName() + "/submit");
Dead code

2017-06-07 11:53 UTC, ljleppan commented on src/main/java/fi/helsinki/cs/tmc/core/communication/TmcServerCommunicationTaskFactory.java
> +                        LOG.log(Level.WARNING, "Downloading adaptive exercise info from skillifier failed.");
Log original exception as well.

2017-06-07 11:53 UTC, ljleppan commented on src/main/java/fi/helsinki/cs/tmc/core/communication/TmcServerCommunicationTaskFactory.java
> +        Set<Exercise> set = new HashSet<>(returnedFromServer.getExercises());
`set` is a really unhelpful name

2017-06-07 11:53 UTC, ljleppan commented on src/main/java/fi/helsinki/cs/tmc/core/domain/Theme.java
> + */
No header comments

2017-06-07 11:53 UTC, ljleppan commented on src/main/java/fi/helsinki/cs/tmc/core/domain/Theme.java
> +        return this.name.equals(exercise.getName().split("-")[0]);
So all adaptive exercises that are part of theme "X" have the name "X-<something>"? This sounds reasonable, but I'd like a small comment here to explicitly spell out this assumption.

2017-06-07 11:53 UTC, ljleppan commented on src/test/java/fi/helsinki/cs/tmc/core/commands/SubmitAdaptiveExerciseToSkillifierTest.java
> +        when(factory.getSkillifierUrl(anyString())).thenReturn(URI.create("www.someurl.com"));
Prefer "www.example.com" as it's reserved by RFC2606. Using anything under the ".test" TLD is also fine as it's similarly reserved.

2017-06-07 11:53 UTC, ljleppan commented on src/main/java/fi/helsinki/cs/tmc/core/domain/Course.java
> +            theme = new Theme(themeName);
@nygrenh Are we still targeting Java 7? If not, I'd rather use `getOrDefault` from Java 8 for things like this.

2017-06-07 11:53 UTC, ljleppan commented on src/test/java/fi/helsinki/cs/tmc/core/domain/CourseTest.java
> +        assertEquals(3,course.getExercises().size());
You aren't really testing the new code here in any capacity beyond `generateThemes()` not producing an exception.

2017-06-07 11:53 UTC, ljleppan commented on src/main/java/fi/helsinki/cs/tmc/core/domain/Course.java
> +    }
**This comment is not a request for change, I'm just trying to get a better understanding of the big picture.**

This method seems to just create the set intersection between the exercises in `theme` and the exercises in `this` course.

I don't fully understand why this is useful: To get all exercises that relate to a certain `Theme` within a certain `Course`, you would already need to have the `Theme` contain all the exercises.

This architecture might be completely valid in the larger picture I'm not seeing, but to me it seems that the signature `public List<Exercise> getExercisesByThemeName(String string)` or something similar would be more helpful.

2017-06-07 11:53 UTC, ljleppan commented on src/main/java/fi/helsinki/cs/tmc/core/communication/TmcServerCommunicationTaskFactory.java
> +                ReviewListParser reviewListParser) {
Are these changes in indetation intended (I.e., fixing previously incorrect indentation)?

2017-06-08 08:24 UTC, Forbaya commented on src/main/java/fi/helsinki/cs/tmc/core/domain/Theme.java
> +        return this.name.equals(exercise.getName().split("-")[0]);
Mavai added a comment in the code.

2017-06-08 10:13 UTC, nygrenh commented on src/main/java/fi/helsinki/cs/tmc/core/domain/Course.java
> +            theme = new Theme(themeName);
Unfortunately we still are.

2017-06-08 10:29 UTC, nygrenh requested changes

2017-06-08 10:29 UTC, nygrenh commented on src/main/java/fi/helsinki/cs/tmc/core/commands/DownloadAdaptiveExercise.java
> +            exercise.setCourseName("None");
Should we log this?

2017-06-08 17:29 UTC, Piia commented on src/main/java/fi/helsinki/cs/tmc/core/domain/Course.java
> +    }
A theme (such as "For-loop") might have exercises related to multiple courses. As a user I can get an adaptive exercise when I have complited all exercises of that theme, so I wrote this method to help checking it in tmc-netbeans.

2017-06-09 09:21 UTC, ljleppan approved these changes

2017-06-12 07:14 UTC, nygrenh approved these changes

2017-06-12 07:14 UTC, merged